package csc.kth.adk14;

import java.io.BufferedOutputStream;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;


public class Concordance {
	private File kFile, k2File, eFile;

	/**
	 * The K file should already exists. K2 and Everest files will be created/generated by this class.
	 * @param kPath input
	 * @param k2Path output
	 * @param everestPath output
	 */
	public Concordance(String kPath, String k2Path, String everestPath) {
		kFile = new File(kPath);
		k2File = new File(k2Path);
		eFile = new File(everestPath);
	}

	/**
	 * Creates a K2 and Everest file from the K file.
	 * K2 contains a list of distinct words and their offset in Everest,
	 * and Everest contains a list of the offsets in S sorted by each word.
	 * 
	 * TODO: write string as bytes instead of UTF8.
	 * @throws Exception sometiemess. dont ask
	 */
	public void generateFromFile() throws Exception {
		BufferedReader kReader = new BufferedReader(
				new InputStreamReader(new FileInputStream(kFile), "ISO-8859-1"));
		DataOutputStream k2Writer = new DataOutputStream(new BufferedOutputStream(
				new FileOutputStream(k2File)));
		DataOutputStream eWriter = new DataOutputStream(new BufferedOutputStream(
				new FileOutputStream(eFile)));
		  
		String lastSaved = "";
		String line;
		long offsetInE = 0;
		int positionSize = Long.SIZE/8;

		while ((line = kReader.readLine()) != null) {
			String[] data = line.split(" "); 
			String currWord = data[0];
			long posInS = Long.valueOf(data[1]);
			if (!currWord.equals(lastSaved)) {
				// Save word in K2 together with corresponding byte offset in E.
				k2Writer.writeUTF(currWord);
				k2Writer.writeLong(offsetInE);
				// Save position in S.
				eWriter.writeLong(posInS);
				lastSaved = currWord;
			} else {
				// The word has previously been added to K2 so only add it to E.
				// Save position in S.
				eWriter.writeLong(posInS);
			}
			offsetInE += positionSize;
		}
		kReader.close();
		k2Writer.close();
		eWriter.close();
	}
	
	
	
	
}
